Models/CommonModels/BreadcrumbViewModel.cs
namespace InventoryManagement.Models.CommonModels
{
    public class BreadcrumbViewModel
    {
        public string Title { get; set; }
        public string Path { get; set; }
        public string ControllerName { get; set; }
        public string Controller { get; set; }


    }
}

Models/PurchaseInvoiceModels/PurchaseInvoiceViewModel.cs
using InventoryManagement.Commons.Enums;
using InventoryManagement.Commons.Extensions;

namespace InventoryManagement.Models.PurchaseInvoiceModels
{
    public class PurchaseInvoiceViewModel
    {
        public string Id { get; set; }
        public string UserName { get; set; }

        public string PartnerId { get; set; }
        public string PartnerName { get; set; }
        public string CompanyName { get; set; }

        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhoneNumber { get; set; }

        public PaymentMethodEnum PaymentMethod { get; set; }
        public InvoiceStatusEnum Status { get; set; }
        public string? Note { get; set; }
        public DateTime CreateAt { get; set; }
        public DateTime UpdateAt { get; set; }
        public float Total { get; set; }
        public InvoiceTypeEnum InvoiceType { get; set; }

        public string TotalToVND
        {
            get
            {
                return Total.FormatVietnameseCurrency();
            }
        }

        public string CreateAtString
        {
            get
            {
                return CreateAt.ToDateOnly();
            }
        }

        public string UpdateAtString
        {
            get
            {
                return UpdateAt.ToDateOnly();
            }
        }
    }
}

Controllers/OauthController.cs
using InventoryManagement.Models.OauthModels;
using InventoryManagement.Services.Contractors;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace InventoryManagement.Controllers
{
    [AllowAnonymous]
    public class OauthController : Controller
    {
        private readonly IOauthService _oauthService;

        public OauthController(IOauthService oauthService)
        {
            _oauthService = oauthService;
        }

        public async Task<IActionResult> Login(string? ReturnUrl)
        {
            var model = new LoginRequest()
            {
                ReturnUrl = ReturnUrl
            };

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequest request)
        {
            if(!ModelState.IsValid) 
            {
                ModelState.AddModelError(string.Empty, "Vui lòng điền đầy đủ thông tin!");
                return View(request);
            }

            var res = await _oauthService.LoginAsync(request);

            if(!res.isSuccess)
            {
                ModelState.AddModelError(string.Empty, res.Message);
                return View(request);
            }

            var user = res.data;

            if (user.ChangePassword == Commons.Enums.ChangePasswordEnum.Unchanged)
            {
                var changePasswordModel = new ChangePasswordRequest()
                {
                    ReturnUrl = request.ReturnUrl,
                    UserId = user.Id.ToString(),
                };

                return RedirectToAction(nameof(ChangePassword), changePasswordModel);
            }

            var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Sid, user.Id),
                    new Claim(ClaimTypes.Name, user.FullName),
                    new Claim(ClaimTypes.Role, user.RoleName),
                };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity)
            );

            return Redirect(request.ReturnUrl ?? "/");
        }

        [Authorize]
        public IActionResult ChangePassword(ChangePasswordRequest request, string ReturlUrl)
        {
            if (request.UserId == null)
                request.UserId = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Sid)?.Value;

            var model = new ChangePasswordRequest()
            {
                ReturnUrl = request.ReturnUrl,
                OldPassword = request.OldPassword,
                UserId = request.UserId,
            };

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordRequest request)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Vui lòng điền đầy đủ thông tin!");
                return View(request);
            }

            var res = await _oauthService.ChangePasswordAsync(request);

            if(!res.isSuccess)
            {
                ModelState.AddModelError(string.Empty, res.Message);
                return View(request);
            }

            return RedirectToAction(nameof(Login), new { returnUrl = request.ReturnUrl });
        }

        public async Task<IActionResult> Logout(string ReturnUrl)
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Login));
        }

        public IActionResult Forbidden()
        {
            return View();
        }

        public IActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ForgotPassword(ForgotPasswordRequest request)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Vui lòng điền đầy đủ thông tin!");
                return View(request);
            }

            var res = await _oauthService.ForgotPasswordAsync(request);

            if (!res.isSuccess)
            {
                ModelState.AddModelError(string.Empty, res.Message);
                return View(request);
            }

            return RedirectToAction(nameof(Login));
        }
    }
}

Controllers/ReportController.cs
using InventoryManagement.Services.Contractors;
using InventoryManagement.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace InventoryManagement.Controllers
{
    [Authorize(Policy = "report")]
    public class ReportController : Controller
    {
        private readonly IReportService _reportService;
        private readonly IPartialViewService _partialViewService;
        private readonly IPdfService _pdfService;

        public ReportController(IReportService reportService,
            IPartialViewService partialViewService,
            IPdfService pdfService)
        {
            _reportService = reportService;
            _partialViewService = partialViewService;
            _pdfService = pdfService;
        }

        [Breadcrumb("Báo cáo nhập kho", "Báo cáo")]
        public async Task<IActionResult> PurchaseReport(DateTime startDate, DateTime endDate)
        {
            if(startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.PurchaseReport(startDate, endDate);

            if (!res.isSuccess)
                return RedirectToAction("Index", "Home");

            return View(res.data);
        }

        public async Task<IActionResult> PurchaseReportToPdf(DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.PurchaseReport(startDate, endDate);

            var html = await _partialViewService.RenderPartialToStringAsync("InventoryInboundReport", res.data);
            var bytes = await _pdfService.HtmlToPdf(html);

            return File(bytes, "application/pdf", "inventory_inbound_Report.pdf");
        }

        [Breadcrumb("Báo cáo xuất kho", "Báo cáo")]
        public async Task<IActionResult> SaleReport(DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.SaleReport(startDate, endDate);

            if (!res.isSuccess)
                return RedirectToAction("Index", "Home");

            return View(res.data);
        }

        public async Task<IActionResult> SaleReportToPdf(DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.SaleReport(startDate, endDate);

            var html = await _partialViewService.RenderPartialToStringAsync("InventoryOutboundReport", res.data);
            var bytes = await _pdfService.HtmlToPdf(html);

            return File(bytes, "application/pdf", "inventory_outbound_Report.pdf");
        }

        [Breadcrumb("Báo cáo doanh thu", "Báo cáo")]
        public async Task<IActionResult> SaleReport2 (DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.SaleReport(startDate, endDate);

            if (!res.isSuccess)
                return RedirectToAction("Index", "Home");

            return View(res.data);
        }


        public async Task<IActionResult> ExportSaleReport2ToPdf(DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var userName = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value;

            var res = await _reportService.SaleReport(startDate, endDate);

            res.data.ReportAuthor = userName;

            var html = await _partialViewService.RenderPartialToStringAsync("SaleReportToPdf", res.data);
            var bytes = await _pdfService.HtmlToPdf(html);

            return File(bytes, "application/pdf", "revenue_report.pdf");
        }

        [Breadcrumb("Báo cáo tồn kho", "Báo cáo")]
        public async Task<IActionResult> InventoryReport()
        {
            var res = await _reportService.InventoryReport();

            if(!res.isSuccess)
                return RedirectToAction("Index", "Home");

            return View(res.data);
        }

        public async Task<IActionResult> InventoryReportToPdf()
        {
            var res = await _reportService.InventoryReport();

            var html = await _partialViewService.RenderPartialToStringAsync("InventoryReportToPdf", res.data);
            var bytes = await _pdfService.HtmlToPdf(html);

            return File(bytes, "application/pdf", "inventory_report.pdf");
        }
    }
}

Controllers/UserController.cs
using Azure;
using InventoryManagement.Commons.Extensions;
using InventoryManagement.Models.CommonModels;
using InventoryManagement.Models.UserModels;
using InventoryManagement.Services.Contractors;
using InventoryManagement.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagement.Controllers
{
    [Authorize(Policy = "admin")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;

        public UserController(IUserService userService, IRoleService roleService)
        {
            _userService = userService;
            _roleService = roleService;
        }

        [Breadcrumb("", "Nhân viên")]
        public async Task<IActionResult> Index()
        {
            if (TempData["ToastNotify"] != null)
            {
                ToastViewModel tempData = TempData.Get<ToastViewModel>("ToastNotify");
                ViewData["ToastNotify"] = tempData;
            }

            var res = await _userService.All();

            return View(res.data);
        }

        [Breadcrumb("Thêm mới", "Nhân viên")]
        public async Task<IActionResult> Create()
        {
            ViewBag.Roles = (await _roleService.All()).data;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserRequest request)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Roles = (await _roleService.All()).data;
                return View(request);
            }

            var res = await _userService.Create(request);

            if (!res.isSuccess)
            {
                ViewBag.Roles = (await _roleService.All()).data;
                return View(request);
            }

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            return RedirectToAction(nameof(Index));
        }

        [Breadcrumb("Cập nhật", "Nhân viên")]
        public async Task<IActionResult> Update(string id) 
        {
            var res = await _userService.Get(id);

            if(!res.isSuccess)
                return RedirectToAction(nameof(Index));

            var data = res.data;

            var updateViewModel = new UpdateUserRequest()
            {
                Id = data.Id,
                FullName = data.FullName,
                RoleId = data.RoleId,
                Dob = data.Dob,
                Sex = data.Sex,
                PhoneNumber = data.PhoneNumber,
                Address = data.Address,
                Email = data.Email,
                IsActive = data.IsActive,
            };

            ViewBag.Roles = (await _roleService.All()).data;

            return View(updateViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateUserRequest request)
        {
            if(!ModelState.IsValid)
            {
                ViewBag.Roles = (await _roleService.All()).data;
                return View(request);
            }

            var res = await _userService.Update(request);

            if (!res.isSuccess)
            {
                ViewBag.Roles = (await _roleService.All()).data;
                ModelState.AddModelError("", res.Message != null ? res.Message : "");
                return View(request);
            }

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string id)
        {
            var res = await _userService.Delete(id);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RecoveryPasswordRequest()
        {
            if (TempData["ToastNotify"] != null)
            {
                ToastViewModel tempData = TempData.Get<ToastViewModel>("ToastNotify");
                ViewData["ToastNotify"] = tempData;
            }

            var res = await _userService.GetRecoveryPasswordsAsync();
            return View(res.data);
        }

        public async Task<IActionResult> ChangePasswordToDefault(string id)
        {
            var res = await _userService.ChangePasswordToDefaultAsync(id);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            return RedirectToAction(nameof(RecoveryPasswordRequest));
        }
    }
}

Views/Shared/_Breadcrumb.cshtml
@using InventoryManagement.Models.CommonModels
@{
    if (ViewData["Breadcrumb"] != null)
    {
        var breadcrumbModel = ViewData["Breadcrumb"] as BreadcrumbViewModel;

        if (!string.IsNullOrEmpty(breadcrumbModel.Path))
        {
            var segments = breadcrumbModel.Path.Split("/");

            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        @{
                            <li class="breadcrumb"><a asp-controller="@breadcrumbModel.Controller" asp-action="Index">&nbsp> @segments[0]</a></li>
                            if (segments.Length > 1)
                            {
                                for (var i = 1; i < segments.Length; i++)
                                {
                                    <li class="breadcrumb-item">
                                        &nbsp> @segments[i]
                                    </li>
                                }
                            }
                        }
                    </ol>
                </nav>
            </div>
        }
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using InventoryManagement.Models.CommonModels
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>@ViewData["Title"]</title>
    <link href="~/iconcp/favicon.png" rel="shortcut icon" type="image/vnd.microsoft.icon">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/layout.css" rel="stylesheet" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="/js/site.js"></script>
    @RenderSection("Style", required: false)
</head>
<body>
    <div class="head d-flex">
        <div class="head-logo"><img src="/iconcp/logo.png"></div>
        <div class="head-welcome">
            <h1>Welcome to Control Panel</h1>
        </div>
        <div class="head-profile">
            <p style="margin:10px 0 5px 0;">Xin chào, <b>@User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value</b>&nbsp;<a class="dtw" asp-controller="Oauth" asp-action="Logout">/ Thoát</a></p>
        </div>
    </div>

    <div id="form1">
        <table class="main-content" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="main-content-left">
                        <div style="border-bottom: #95b3de 1px solid; text-align:center; padding:5px;"><a asp-controller="Home" asp-action="Index">Control Panel Home</a></div>
                        <div style="border-top: #ffffff 1px solid; height:10px;"><img src="/iconcp/null.gif"></div>
                        <div class="col-left">
                            <div class="title-left">Quản lý danh mục</div>
                            <a class="menuleft" asp-controller="Warehouse" asp-action="index"><img class="imgmid" src="/iconcp/icon_menu.png"> Danh mục kho hàng</a>
                            <a class="menuleft" asp-controller="Category" asp-action="index"><img class="imgmid" src="/iconcp/icon_menu.png"> Danh mục nhóm hàng</a>
                            <a class="menuleft" asp-controller="Product" asp-action="index"><img class="imgmid" src="/iconcp/icon_menu.png"> Danh mục hàng hóa</a>
                            <a class="menuleft" asp-controller="Partner" asp-action="index"><img class="imgmid" src="/iconcp/icon_menu.png"> Danh mục nhà cung cấp</a>
                            <a class="menuleft" asp-controller="Customer" asp-action="index"><img class="imgmid" src="/iconcp/icon_menu.png"> Danh mục khách hàng</a>
                            <a class="menuleft" asp-controller="User" asp-action="index"><img class="imgmid" src="/iconcp/icon_menu.png"> Danh mục nhân viên</a>

                            <div class="title-left">Quản lý xuất kho</div>
                            <a class="menuleft" asp-controller="SaleInvoice" asp-action="Index"><img class="imgmid" src="/iconcp/icon_pro.png">Danh sách hóa đơn xuất</a>
                            <a class="menuleft" asp-controller="SaleInvoice" asp-action="Create"><img class="imgmid" src="/iconcp/icon_pro.png">Xuất kho bán hàng</a>
                            <a class="menuleft" asp-controller="SaleInvoice" asp-action="Return"><img class="imgmid" src="/iconcp/icon_pro.png">Xuất kho trả hàng NCC</a>

                            <div class="title-left">Quản lý nhập kho</div>
                            <a class="menuleft" asp-controller="PurchaseInvoice" asp-action="Index"><img class="imgmid" src="/iconcp/icon_pro.png">Danh sách hóa đơn nhập</a>
                            <a class="menuleft" asp-controller="PurchaseInvoice" asp-action="Create"><img class="imgmid" src="/iconcp/icon_pro.png">Nhập kho bán hàng</a>
                            <a class="menuleft" asp-controller="PurchaseInvoice" asp-action="Return"><img class="imgmid" src="/iconcp/icon_pro.png">Nhập hàng trả lại từ KH</a>

                            <div class="title-left">Quản lý tồn kho</div>
                            <a class="menuleft" asp-controller="Warehouse" asp-action="ProductReport"><img class="imgmid" src="/iconcp/icon_pro.png">Theo dõi số lượng tồn kho</a>
                            <a class="menuleft" asp-controller="Warehouse" asp-action="MonthlyProductReport"><img class="imgmid" src="/iconcp/icon_pro.png">Tổng hợp tồn kho</a>
                            <a class="menuleft" asp-controller="Warehouse" asp-action="UpdateWarehouse"><img class="imgmid" src="/iconcp/icon_pro.png">Kiểm kê kho</a>

                            <div class="title-left">Báo cáo thống kê</div>
                            <a class="menuleft" asp-controller="Report" asp-action="SaleReport2"><img class="imgmid" src="/iconcp/icon_pro.png">Báo cáo doanh thu bán hàng</a>
                            <a class="menuleft" asp-controller="Report" asp-action="InventoryReport"><img class="imgmid" src="/iconcp/icon_pro.png">Báo cáo tồn kho</a>
                            <a class="menuleft" asp-controller="Report" asp-action="PurchaseReport"><img class="imgmid" src="/iconcp/icon_news.png"> Báo cáo nhập kho</a>
                            <a class="menuleft" asp-controller="Report" asp-action="SaleReport"><img class="imgmid" src="/iconcp/icon_media.png"> Báo cáo xuất kho</a>

                            <div class="title-left">Khác</div>
                            <a class="menuleft" href="@Url.Action("ChangePassword", "Oauth", new { returnUrl = Context.Request.Path})"><img class="imgmid" src="/iconcp/icon_pass.png"> Đổi mật khẩu</a>
                            <a class="menuleft" asp-controller="Oauth" asp-action="Logout" onclick="javascript:return confirm('Bạn thật sự muốn thoát không?')"><img class="imgmid" src="iconcp/icon_logout.png"> Thoát</a>
                        </div>
                    </td>
                    <td class="main-content-right">
                        <div class="main-content-nav">
                            <h1 class="main-title"><span id="lblLink">@ViewData["Title"]</span></h1>
                            @await Html.PartialAsync("~/Views/Shared/_Breadcrumb.cshtml")
                        </div>
                        @RenderBody()
                    </td>
                </tr>
            </tbody>
        </table>
        <table class="footer" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td style="padding:10px;">Xem tốt nhất trên trình duyệt Firefox hoặc Chrome với độ phân giải 1366x768 px</td>
                    <td style="text-align:right; padding:10px;">All Right Reserved by Đặng Hương Giang</td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

<script>
    let table = new DataTable('#dtgrView', {
        responsive: true,
        processing: true,
        lengthMenu: [15, 25, 50, 100],
    });

    let history = new DataTable('.dtgrView', {
        responsive: true,
        processing: true,
        lengthMenu: [5, 10],
    });
</script>

@{
    var toastNotify = ViewData["ToastNotify"] as ToastViewModel;

    if (toastNotify != null)
    {
        var message = toastNotify.Message;
        switch (toastNotify.IsSuccess)
        {
            case true:
                <script>
                    toastr.success('@message');
                </script>
                break;
            case false:
                <script>
                    toastr.error('@message');
                </script>
                break;
        }
    }
}

@RenderSection("Scripts", required: false)