Models/ReportModels/MonthlyProductReportViewModel.cs
namespace InventoryManagement.Models.ReportModels
{
    public class MonthlyProductReportViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public float Quantity { get; set; }
        public string Unit { get; set; }
        public float? AmountPurchaseCurrentMonth { get; set; }
        public int? QuantityImportCurrentMonth { get; set; }
        public float? AmountPurchaseLastMonth { get; set;}
        public int? QuantityImportLastMonth { get; set; }

        public float AmountSaleCurrentMonth { get; set; }
        public int? QuantitySoldCurrentMonth { get; set; }
        public float AmountSaleLastMonth { get; set;}
        public int? QuantitySoldLastMonth { get; set; }

        public float? DifferenceImport
        {
            get
            {
                if (AmountPurchaseCurrentMonth == 0)
                    return 0;
                else if (AmountPurchaseLastMonth == 0)
                    return 100;
                else
                {
                    var deffrence = ((AmountPurchaseCurrentMonth - AmountPurchaseLastMonth) / AmountPurchaseLastMonth) * 100;
                    return (float?)Math.Round((decimal)deffrence, 2);
                }    
            }
        }

        public float? DifferenceSale
        {
            get
            {
                if (AmountSaleCurrentMonth == 0)
                    return 0;
                else if (AmountSaleLastMonth == 0)
                    return 100;
                else
                    return ((AmountSaleCurrentMonth - AmountSaleLastMonth) / AmountSaleLastMonth) * 100;
            }
        }
    }
}

Models/WarehouseModels/WarehouseViewModel.cs
using InventoryManagement.Commons.Enums;

namespace InventoryManagement.Models.WarehouseModels
{
    public class WarehouseViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public float StorageCapacity { get; set; }
        public float? Area { get; set; }
        public string Unit { get; set; }
        public string? Description { get; set; }
        public WarehouseCapacityEnum WarehouseCapacity { get; set; }

        public string WarehouseCapacityString {
            get {
                if (WarehouseCapacity == WarehouseCapacityEnum.Empty)
                    return "Còn trống";
                else
                    return "Đã đầy";
            }
        }
    }
}

Controllers/ProductController.cs
using Azure;
using InventoryManagement.Commons.Extensions;
using InventoryManagement.Models.CommonModels;
using InventoryManagement.Models.MerchandiseModels;
using InventoryManagement.Services.Contractors;
using InventoryManagement.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagement.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IWarehouseService _warehouseService;
        private readonly ICategoryService _categoryService;
        private readonly IReportService _reportService;

        public ProductController(IProductService productService, 
            IWarehouseService warehouseService, 
            ICategoryService categoryService, 
            IReportService reportService)
        {
            _productService = productService;
            _warehouseService = warehouseService;
            _categoryService = categoryService;
            _reportService = reportService;
        }

        public async Task<IActionResult> All()
        {
            var res = await _productService.All();
            return Ok(res.data);
        }

        [Authorize(Policy = "productAccess")]
        [Breadcrumb("", "Sản phẩm")]
        public async Task<IActionResult> Index()
        {
            if (TempData["ToastNotify"] != null)
            {
                ToastViewModel tempData = TempData.Get<ToastViewModel>("ToastNotify");
                ViewData["ToastNotify"] = tempData;
            }

            var res = await _productService.All();
            return View(res.data);
        }

        [Authorize(Policy = "warehouse")]
        [Breadcrumb("Thêm mới", "Sản phẩm")]
        public async Task<IActionResult> Create()
        {
            var warehouses = await _warehouseService.All();
            var categories = await _categoryService.All();

            ViewBag.Warehouses = warehouses.data;
            ViewBag.Categories = categories.data;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductRequest request) 
        {
            if (!ModelState.IsValid)
            {
                var warehouses = await _warehouseService.All();
                var categories = await _categoryService.All();

                ViewBag.Warehouses = warehouses.data;
                ViewBag.Categories = categories.data;

                return View(request);
            }

            var res = await _productService.Create(request);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            if (!res.isSuccess)
            {
                return View(request);
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "warehouse")]
        [Breadcrumb("Cập nhật", "Sản phẩm")]
        public async Task<IActionResult> Update(string id)
        {
            var warehouses = await _warehouseService.All();
            var categories = await _categoryService.All();

            ViewBag.Warehouses = warehouses.data;
            ViewBag.Categories = categories.data;

            var product = (await _productService.Get(id)).data;

            var updateProductRequest = new UpdateProductRequest()
            {
                Id = id,
                CategoryId = product.CategoryId,
                WarehouseId = product.WarehouseId,
                Name = product.Name,
                Price = product.Price,
                Quantity = product.Quantity,
                Unit = product.Unit,
                Description = product.Description,
                Image = product.Image,
                IsActive = product.IsActive,
            };

            return View(updateProductRequest);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateProductRequest request)
        {
            if(!ModelState.IsValid) 
                return View(request);

            var res = await _productService.Update(request);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            if (!res.isSuccess)
                return View(request);

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "admin")]
        public async Task<IActionResult> Delete(string id)
        {
            var res = await _productService.Delete(id);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/WarehouseController.cs
using Azure;
using InventoryManagement.Commons.Extensions;
using InventoryManagement.Models.CommonModels;
using InventoryManagement.Models.WarehouseModels;
using InventoryManagement.Services.Contractors;
using InventoryManagement.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagement.Controllers
{
    [Authorize(Policy = "warehouse")]
    public class WarehouseController : Controller
    {
        private readonly IWarehouseService _warehouseService;
        private readonly IReportService _reportService;
        private readonly IProductService _productService;
        private readonly IPurchaseInvoiceService _purchaseInvoiceService;   
        private readonly IMerchandisePurchaseInvoiceService _merchandisePurchaseInvoiceService;

        public WarehouseController(IWarehouseService warehouseService,
            IReportService reportService,
            IProductService productService,
            IPurchaseInvoiceService purchaseInvoiceService,
            IMerchandisePurchaseInvoiceService merchandisePurchaseInvoiceService)
        {
            _warehouseService = warehouseService;
            _reportService = reportService;
            _productService = productService;
            _purchaseInvoiceService = purchaseInvoiceService;
            _merchandisePurchaseInvoiceService = merchandisePurchaseInvoiceService;
        }

        [Breadcrumb("", "Kho hàng")]
        public async Task<IActionResult> Index()
        {
            if (TempData["ToastNotify"] != null)
            {
                ToastViewModel tempData = TempData.Get<ToastViewModel>("ToastNotify");
                ViewData["ToastNotify"] = tempData;
            }

            var response = await _warehouseService.All();

            return View(response.data);
        }

        [Authorize(Policy = "admin")]
        [Breadcrumb("Thêm mới", "Kho hàng")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateWarehouseRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var response = await _warehouseService.Create(request);

            if (!response.isSuccess)
            {
                return View(request);
            }

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = response.isSuccess,
                Message = response.Message,
            });

            return RedirectToAction(nameof(Index));
        }

        [Breadcrumb("Cập nhật", "Kho hàng")]
        public async Task<IActionResult> Update(string id)
        {
            var res = await _warehouseService.Get(id);

            if(!res.isSuccess)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new UpdateWarehouseRequest()
            {
                Id = id,
                Name = res.data.Name,
                Area = res.data.Area,
                Description = res.data.Description,
                WarehouseCapacity = res.data.WarehouseCapacity,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateWarehouseRequest request)
        {
            if(!ModelState.IsValid)
                return View(request);

            var response = await _warehouseService.Update(request);

            if(!response.isSuccess)
            {
                ModelState.AddModelError("", response.Message != null ? response.Message : "");
                return View(request);
            }

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = response.isSuccess,
                Message = response.Message,
            });

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "admin")]
        public async Task<IActionResult> Delete(string id) 
        {   
            var res = await _warehouseService.Delete(id);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "warehouseReport")]
        [HttpGet("product-report")]
        [Breadcrumb("Theo dõi số lượng tồn kho", "Kho hàng")]
        public async Task<IActionResult> ProductReport()
        {
            var res = await _productService.All();

            return View(res.data);
        }

        [Authorize(Policy = "warehouseReport")]
        [HttpGet("product-monthly")]
        [Breadcrumb("Tổng hợp tồn kho", "Kho hàng")]
        public async Task<IActionResult> MonthlyProductReport(DateTime date)
        {
            if (date == DateTime.MinValue)
            {
                date = DateTime.Now;
            }

            var res = await _reportService.MonthlyProductReport(date);

            ViewBag.Date = date;
            return View(res.data);
        }

        [Authorize(Policy = "updateWarehouse")]
        [Breadcrumb("Kiểm kê kho", "Kho hàng")]
        public async Task<IActionResult> UpdateWarehouse()
        {
            var res = await _purchaseInvoiceService.AllUnUpdateWarehouseInvoiceAsync();

            var data = res.data;

            return View(data);
        }

        [Authorize(Policy = "updateWarehouse")]
        [Breadcrumb("Kiểm kê kho", "Kho hàng")]
        public async Task<IActionResult> ConfirmUpdateWarehouse(string id)
        {
            var getInvoiceRes = await _purchaseInvoiceService.GetAsync(id);
            if (!getInvoiceRes.isSuccess || getInvoiceRes.data == null)
                return RedirectToAction(nameof(Index));
            var invoice = getInvoiceRes.data;

            var getInvoiceDetailRes = await _merchandisePurchaseInvoiceService.GetByInvoiceAsync(id);
            if (!getInvoiceDetailRes.isSuccess || getInvoiceDetailRes.data == null)
                return RedirectToAction(nameof(Index));

            var invoiceDetails = getInvoiceDetailRes.data;

            var data = new UpdateInventoryRequest()
            {
                PurchaseInvoiceViewModel = invoice,
                MerchandisePurchaseViewModels = invoiceDetails,
            };

            return View(data);
        }


        [HttpPost]
        [Authorize(Policy = "updateWarehouse")]
        public async Task<IActionResult> UpdateWarehouse(UpdateInventoryRequest request)
        {
            var res = await _warehouseService.UpdateInventoryAsync(request);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            return RedirectToAction("index", "product");
        }
    }
}

Views/Warehouse/ConfirmUpdateWarehouse.cshtml
@using InventoryManagement.Commons.Enums
@model InventoryManagement.Models.WarehouseModels.UpdateInventoryRequest
@{
    ViewData["Title"] = "Chi tiết hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var invoice = Model.PurchaseInvoiceViewModel;
    var invoiceDetails = Model.MerchandisePurchaseViewModels;
}

<form asp-action="UpdateWarehouse" asp-controller="Warehouse" method="post">
    <input type="hidden" asp-for="@Model.PurchaseInvoiceViewModel.Id" />
    <table id="tblAdd" style="width:100%;" cellpadding="0" cellspacing="1">
        <tbody>
            @{
                var invoiceType = "";
                if (invoice.InvoiceType == InvoiceTypeEnum.Invoice)
                {
                    invoiceType = "Hóa đơn nhập hàng từ NCC";
                }
                else
                {
                    invoiceType = "Hóa đơn nhập hàng từ KH";
                }
            }
            <tr class="tr-view">
                <td colspan="2" class="td-view-left">
                    <input type="submit" name="btnAddU1" value="Cập nhật kho" id="btnAddU1" class="button">
                </td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Loại hóa đơn:</div></td>
                <td class="td2"><input readonly value="@invoiceType" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
            </tr>
            @if (invoice.InvoiceType == InvoiceTypeEnum.Invoice)
            {
                <tr>
                    <td class="td1"><div style="width:105px;">Nhà cung cấp:</div></td>
                    <td class="td2"><input readonly value="@invoice.CompanyName" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
                </tr>
            }
            else
            {
                <tr>
                    <td class="td1"><div style="width:105px;">Tên khách hàng:</div></td>
                    <td class="td2"><input readonly value="@invoice.CustomerName" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
                </tr>
            }
            <tr>
                <td class="td1"><div style="width:105px;">Ngày lập:</div></td>
                <td class="td2"><input readonly value="@invoice.CreateAtString" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Ngày sửa gần nhất:</div></td>
                <td class="td2"><input readonly value="@invoice.UpdateAtString" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1">Ghi chú:</td>
                <td class="td2"><textarea rows="8" cols="20" class="textbox" style="width:98%;">@invoice.Note</textarea></td>
            </tr>
            <tr>
                <td class="td1">Danh sách sản phẩm: </td>
                <td class="td2">
                    <table id="merchandiseTable" class="table">
                        <thead class="thead">
                            <tr>
                                <th class="th">Mã sản phẩm</th>
                                <th class="th">Tên sản phẩm</th>
                                <th class="th">Giá mua</th>
                                <th class="th">Số lượng</th>
                            </tr>
                        </thead>
                        <tbody class="tbody">
                            @for (var index = 0; index < Model.MerchandisePurchaseViewModels.Count; index++)
                            {
                                var item = Model.MerchandisePurchaseViewModels[index];

                                <tr>
                                    <td class="td">
                                        @item.MerchandiseId
                                        <input type="hidden" readonly name="MerchandisePurchaseViewModels[@index].MerchandiseId" value="@item.MerchandiseId" />
                                    </td>
                                    <td class="td">
                                        @item.MerchandiseName
                                    </td>
                                    <td class="td">
                                        @item.PurchasePriceToVND
                                        <input type="hidden" readonly name="MerchandisePurchaseViewModels[@index].PurchasePrice" value="@item.PurchasePrice" />
                                    </td>
                                    <td class="td">
                                        @item.Quantity
                                        <input type="hidden" readonly name="MerchandisePurchaseViewModels[@index].Quantity" value="@item.Quantity" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</form>

Views/Warehouse/Create.cshtml
@model InventoryManagement.Models.WarehouseModels.CreateWarehouseRequest
@{
    ViewData["Title"] = "Thêm kho hàng mới";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Create" asp-controller="Warehouse" method="post">
    <table id="tblAdd" style="width:100%;" cellpadding="0" cellspacing="1">
        <tbody>
            <tr class="tr-view">
                <td colspan="2" class="td-view-left">
                    <input type="submit" value="Ghi nhận" id="btnAddU1" class="button">
                    <input type="reset" class="button" value="Mặc định">
                </td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Tên kho:</div></td>
                <td class="td2"><input type="text" maxlength="150" asp-for="Name" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1">Diện tích:</td>
                <td class="td2"><input type="text" maxlength="50" asp-for="Area" class="textbox" style="width:250px;"></td>
            </tr>
            <tr>
                <td class="td1">Mô tả ngắn:</td>
                <td class="td2"><textarea rows="8" cols="20" asp-for="Description" class="textbox" style="width:98%;"></textarea></td>
            </tr>
            <tr>
                <td class="td1">&nbsp;</td>
                <td class="td1" style="text-align:left;">
                    <input type="submit" value="Ghi nhận" class="button" style="width:100px;">
                    <input type="reset" class="button" value="Mặc định" style="width:100px;">
                </td>
            </tr>
        </tbody>
    </table>
</form>

Views/Warehouse/Index.cshtml
@model List<InventoryManagement.Models.WarehouseModels.WarehouseViewModel>
@{
    ViewData["Title"] = "Danh mục kho hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="tblView" style="width:100%;" cellpadding="0" cellspacing="0">
    <tbody>
        <tr class="tr-view">
            <td class="td-view-left">
            </td>
            <td class="td-view-right">
                <a asp-action="Create" class="button btn-add">Thêm mới</a>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table class="table table-striped table-bordered" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" id="dtgrView" style="border-style:None;width:100%;border-collapse:collapse;">
                    <thead>
                        <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                            <td>Tên</td>
                            <td>Mô tả</td>
                            <td>Diện tích</td>
                            <td>Trạng thái kho</td>
                            <td style="width:10px;">&nbsp;Sửa&nbsp;</td>
                            <td style="width:10px;">&nbsp;Xóa&nbsp;</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.Description)</td>
                                <td>@Html.DisplayFor(modelItem => item.Area) m<sup>2</sup></td>
                                <td>@Html.DisplayFor(modelItem => item.WarehouseCapacityString)</td>
                                <td align="center"><a href="@Url.Action("Update", "Warehouse", new { id = item.Id })"><img border="0" src="iconcp/icon_edit.gif"></a></td>
                                <td align="center"><a onclick="javascript:return confirm('Nếu bạn xoá menu (Danh mục sản phẩm) thì toàn bộ menu cấp 2 thuộc menu (Danh mục sản phẩm) sẽ bị xoá theo. Bạn chắc chắn muốn xoá menu (Danh mục sản phẩm) không?');" href="@Url.Action("Delete", "Warehouse", new { id = item.Id })"><img border="0" src="iconcp/icon_delete.gif"></a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>

Views/Warehouse/MonthlyProductReport.cshtml
@model List<InventoryManagement.Models.ReportModels.MonthlyProductReportViewModel>

@{
    DateTime date = ViewBag.Date;
    if (date == DateTime.MinValue)
        date = DateTime.Now;

    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Tổng hợp tồn kho tháng " + date.Month + " năm " + date.Year;
}
<form method="get" asp-action="MonthlyProductReport" asp-controller="Warehouse">
    <table id="tblView" style="width:100%;" cellpadding="0" cellspacing="0">
        <tbody>
            <tr class="tr-view">
                <td class="td-view-left">
                    <input type="submit" id="btnUpdate1" class="button" value="Lọc">
                    <input type="date" name="date" value="@date"/>
                </td>
                <td class="td-view-right">
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <table class="table table-striped table-bordered" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" id="dtgrView" style="border-style:None;width:100%;border-collapse:collapse;">
                        <thead>
                            <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                                <td>Tên</td>
                                <td>Tồn kho hiện tại</td>
                                <td>Số lượng nhập trong tháng</td>
                                <td>Số lượng bán trong tháng</td>
                                <td>Đơn vị tính</td>
                                <td style="width:10px;">&nbsp;Chi tiết&nbsp;</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                                    <td>
                                        <div class="difference-td">
                                            <span class="quantity">@Html.DisplayFor(modelItem => item.QuantityImportCurrentMonth)</span>
                                            <div class="difference">
                                                @{
                                                    var src = "";
                                                    if (item.DifferenceImport >= 0)
                                                        src = "/iconcp/increase.png";
                                                    else
                                                        src = "/iconcp/decrease.png";
                                                }
                                                <img src="@src" class="icon" />
                                                <span class="detail">@item.DifferenceImport %</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="difference-td">
                                            <span class="quantity">@Html.DisplayFor(modelItem => item.QuantitySoldCurrentMonth)</span>
                                            <div class="difference">
                                                @{
                                                    if (item.DifferenceSale >= 0)
                                                        src = "/iconcp/increase.png";
                                                    else
                                                        src = "/iconcp/decrease.png";
                                                }
                                                <img src="@src" class="icon" />
                                                <span class="detail">@item.DifferenceSale %</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>@Html.DisplayFor(modelItem => item.Unit)</td>
                                    <td align="center"><a href="@Url.Action("Update", "Product", new { id = item.Id })"><img border="0" src="/iconcp/preview.png"></a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</form>

Views/Warehouse/ProductReport.cshtml
@using InventoryManagement.Commons.Enums
@using InventoryManagement.Models.MerchandiseModels
@model List<ProductViewModel>
@{
    ViewData["Title"] = "Theo dõi số lượng tồn kho";
}

<table id="tblView" style="width:100%;" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td colspan="2">
                <table class="table table-striped table-bordered" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" id="dtgrView" style="border-style:None;width:100%;border-collapse:collapse;">
                    <thead>
                        <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                            <td>Tên sản phẩm</td>
                            <td>Giá bán</td>
                            <td>Số lượng</td>
                            <td style="width:10px;">&nbsp;Sửa&nbsp;</td>
                            <td style="width:10px;">&nbsp;Xóa&nbsp;</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            var activeEnums = Enum.GetValues(typeof(ActiveEnum));
                            var style = item.Quantity <= 10 ? "background-color: #f81717; color: #fff" : "";
                            <tr style="@style">
                                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.PriceToVND)</td>
                                <td>@Html.DisplayFor(modelItem => item.Quantity) @Html.DisplayFor(modelItem => item.Unit)</td>
                                <td align="center"><a href="@Url.Action("Update", "Product", new { id = item.Id })"><img border="0" src="/iconcp/icon_edit.gif"></a></td>
                                <td align="center"><a href="@Url.Action("Delete", "Product", new { id = item.Id })" onclick="javascript:return confirm('Bạn chắc chắn muốn xoá Sản phẩm không?');"><img border="0" src="/iconcp/icon_delete.gif"></a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>