Models/ReportModels/InventoryReportViewModel.cs
using InventoryManagement.Models.MerchandiseModels;

namespace InventoryManagement.Models.ReportModels
{
    public class InventoryReportViewModel
    {
        public string WarehouseName { get; set; }
        public List<ProductViewModel> products { get; set; }
    }
}

Controllers/ProductController.cs
using Azure;
using InventoryManagement.Commons.Extensions;
using InventoryManagement.Models.CommonModels;
using InventoryManagement.Models.MerchandiseModels;
using InventoryManagement.Services.Contractors;
using InventoryManagement.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagement.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IWarehouseService _warehouseService;
        private readonly ICategoryService _categoryService;
        private readonly IReportService _reportService;

        public ProductController(IProductService productService, 
            IWarehouseService warehouseService, 
            ICategoryService categoryService, 
            IReportService reportService)
        {
            _productService = productService;
            _warehouseService = warehouseService;
            _categoryService = categoryService;
            _reportService = reportService;
        }

        public async Task<IActionResult> All()
        {
            var res = await _productService.All();
            return Ok(res.data);
        }

        [Authorize(Policy = "productAccess")]
        [Breadcrumb("", "Sản phẩm")]
        public async Task<IActionResult> Index()
        {
            if (TempData["ToastNotify"] != null)
            {
                ToastViewModel tempData = TempData.Get<ToastViewModel>("ToastNotify");
                ViewData["ToastNotify"] = tempData;
            }

            var res = await _productService.All();
            return View(res.data);
        }

        [Authorize(Policy = "warehouse")]
        [Breadcrumb("Thêm mới", "Sản phẩm")]
        public async Task<IActionResult> Create()
        {
            var warehouses = await _warehouseService.All();
            var categories = await _categoryService.All();

            ViewBag.Warehouses = warehouses.data;
            ViewBag.Categories = categories.data;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductRequest request) 
        {
            if (!ModelState.IsValid)
            {
                var warehouses = await _warehouseService.All();
                var categories = await _categoryService.All();

                ViewBag.Warehouses = warehouses.data;
                ViewBag.Categories = categories.data;

                return View(request);
            }

            var res = await _productService.Create(request);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            if (!res.isSuccess)
            {
                return View(request);
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "warehouse")]
        [Breadcrumb("Cập nhật", "Sản phẩm")]
        public async Task<IActionResult> Update(string id)
        {
            var warehouses = await _warehouseService.All();
            var categories = await _categoryService.All();

            ViewBag.Warehouses = warehouses.data;
            ViewBag.Categories = categories.data;

            var product = (await _productService.Get(id)).data;

            var updateProductRequest = new UpdateProductRequest()
            {
                Id = id,
                CategoryId = product.CategoryId,
                WarehouseId = product.WarehouseId,
                Name = product.Name,
                Price = product.Price,
                Quantity = product.Quantity,
                Unit = product.Unit,
                Description = product.Description,
                Image = product.Image,
                IsActive = product.IsActive,
            };

            return View(updateProductRequest);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateProductRequest request)
        {
            if(!ModelState.IsValid) 
                return View(request);

            var res = await _productService.Update(request);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            if (!res.isSuccess)
                return View(request);

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "admin")]
        public async Task<IActionResult> Delete(string id)
        {
            var res = await _productService.Delete(id);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/ReportController.cs
using InventoryManagement.Services.Contractors;
using InventoryManagement.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace InventoryManagement.Controllers
{
    [Authorize(Policy = "report")]
    public class ReportController : Controller
    {
        private readonly IReportService _reportService;
        private readonly IPartialViewService _partialViewService;
        private readonly IPdfService _pdfService;

        public ReportController(IReportService reportService,
            IPartialViewService partialViewService,
            IPdfService pdfService)
        {
            _reportService = reportService;
            _partialViewService = partialViewService;
            _pdfService = pdfService;
        }

        [Breadcrumb("Báo cáo nhập kho", "Báo cáo")]
        public async Task<IActionResult> PurchaseReport(DateTime startDate, DateTime endDate)
        {
            if(startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.PurchaseReport(startDate, endDate);

            if (!res.isSuccess)
                return RedirectToAction("Index", "Home");

            return View(res.data);
        }

        public async Task<IActionResult> PurchaseReportToPdf(DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.PurchaseReport(startDate, endDate);

            var html = await _partialViewService.RenderPartialToStringAsync("InventoryInboundReport", res.data);
            var bytes = await _pdfService.HtmlToPdf(html);

            return File(bytes, "application/pdf", "inventory_inbound_Report.pdf");
        }

        [Breadcrumb("Báo cáo xuất kho", "Báo cáo")]
        public async Task<IActionResult> SaleReport(DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.SaleReport(startDate, endDate);

            if (!res.isSuccess)
                return RedirectToAction("Index", "Home");

            return View(res.data);
        }

        public async Task<IActionResult> SaleReportToPdf(DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.SaleReport(startDate, endDate);

            var html = await _partialViewService.RenderPartialToStringAsync("InventoryOutboundReport", res.data);
            var bytes = await _pdfService.HtmlToPdf(html);

            return File(bytes, "application/pdf", "inventory_outbound_Report.pdf");
        }

        [Breadcrumb("Báo cáo doanh thu", "Báo cáo")]
        public async Task<IActionResult> SaleReport2 (DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var res = await _reportService.SaleReport(startDate, endDate);

            if (!res.isSuccess)
                return RedirectToAction("Index", "Home");

            return View(res.data);
        }


        public async Task<IActionResult> ExportSaleReport2ToPdf(DateTime startDate, DateTime endDate)
        {
            if (startDate == DateTime.MinValue)
                startDate = DateTime.Now;

            if (endDate == DateTime.MinValue)
                endDate = startDate.AddMonths(-1);

            var userName = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value;

            var res = await _reportService.SaleReport(startDate, endDate);

            res.data.ReportAuthor = userName;

            var html = await _partialViewService.RenderPartialToStringAsync("SaleReportToPdf", res.data);
            var bytes = await _pdfService.HtmlToPdf(html);

            return File(bytes, "application/pdf", "revenue_report.pdf");
        }

        [Breadcrumb("Báo cáo tồn kho", "Báo cáo")]
        public async Task<IActionResult> InventoryReport()
        {
            var res = await _reportService.InventoryReport();

            if(!res.isSuccess)
                return RedirectToAction("Index", "Home");

            return View(res.data);
        }

        public async Task<IActionResult> InventoryReportToPdf()
        {
            var res = await _reportService.InventoryReport();

            var html = await _partialViewService.RenderPartialToStringAsync("InventoryReportToPdf", res.data);
            var bytes = await _pdfService.HtmlToPdf(html);

            return File(bytes, "application/pdf", "inventory_report.pdf");
        }
    }
}

Views/Report/InventoryReport.cshtml
@model List<InventoryManagement.Models.ReportModels.InventoryReportViewModel>
@{
    ViewData["Title"] = "Báo cáo tồn kho";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="tblAdd" style="width:100%;" cellpadding="0" cellspacing="1">
    <tr class="tr-view">
        <td class="td-view-left d-flex align-items-center">
            <a href="@Url.Action("InventoryReportToPdf", "Report")" class="button btn-add">In báo cáo</a>
        </td>
        <td class="td-view-right">
        </td>
    </tr>
</table>

@foreach (var model in Model)
{
    <div class="history-table-title">@Html.DisplayFor(modelItem => model.WarehouseName)</div>
    <table class="table table-striped table-bordered dtgrView" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" style="border-style:None;width:100%;border-collapse:collapse;">
        <thead>
            <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                <td></td>
                <td>Tên sản phẩm</td>
                <td>Giá bán</td>
                <td>Số lượng tồn trong kho</td>
                <td>Đơn vị tính</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in model.products)
            {
                <tr>
                    <td style="text-align: center;"><img style="width: 60px" src="@Html.DisplayFor(modelItem => item.Image)" /></td>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.PriceToVND)</td>
                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                    <td>@Html.DisplayFor(modelItem => item.Unit)</td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Report/PurchaseReport.cshtml
@model InventoryManagement.Models.ReportModels.InvoiceReportViewModel
@{
    ViewData["Title"] = "Báo cáo nhập kho";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form asp-action="PurchaseReport" method="get">
    <table id="tblAdd" style="width:100%;" cellpadding="0" cellspacing="1">
        <tr class="tr-view">
            <td class="td-view-right">
                <a href="@Url.Action("PurchaseReportToPdf", "Report", new { startDate = Model.StartDate, endDate = Model.EndDate})" class="button btn-add">In báo cáo</a>
            </td>
            <td class="td-view-left d-flex align-items-center">
                <input type="submit" id="btnUpdate1" class="button" value="Lọc">
                <div class="ms-3 date-filter">
                    <span style="color:#ccc">Từ: </span>
                    <input type="date" name="endDate" value="@Model.EndDateString" />
                    <span style="color:#ccc">Đến: </span>
                    <input type="date" name="startDate" value="@Model.StartDateString" />
                </div>
            </td>
        </tr>
        <tbody>
            <tr>
                <td class="td1"><div style="width:105px;">Thời gian:</div></td>
                <td class="td2">@Html.DisplayFor(modelItem => modelItem.EndDateString) - @Html.DisplayFor(modelItem => modelItem.StartDateString)</td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Tổng tiền nhập từ NCC:</div></td>
                <td class="td2">@Html.DisplayFor(modelItem => modelItem.TotalAmountToVND)</td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Tổng tiền nhập từ KH:</div></td>
                <td class="td2">@Html.DisplayFor(modelItem => modelItem.TotalReturnAmountToVND)</td>
            </tr>
        </tbody>
    </table>

    <div class="history-table-title">Báo cáo nhập hàng</div>
    <table class="table table-striped table-bordered dtgrView" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" style="border-style:None;width:100%;border-collapse:collapse;">
        <thead>
            <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                <td>Tên hàng</td>
                <td>Số lượng</td>
                <td>Đơn vị tính</td>
                <td>Tổng tiền</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Details)
            {
                if (item.InvoiceType == InventoryManagement.Commons.Enums.InvoiceTypeEnum.Invoice)
                {
                    <tr>
                        <td><a @Url.Action("Update", "Product", new { id = item.Id })>@Html.DisplayFor(modelItem => item.Name)</a></td>
                        <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                        <td>@Html.DisplayFor(modelItem => item.Unit)</td>
                        <td>@Html.DisplayFor(modelItem => item.TotalToString)</td>
                    </tr>
                }
            }
        </tbody>
    </table>

    <div class="history-table-title">Báo cáo nhập hàng trả lại từ KH</div>
    <table class="table table-striped table-bordered dtgrView" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" style="border-style:None;width:100%;border-collapse:collapse;">
        <thead>
            <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                <td>Tên hàng</td>
                <td>Số lượng</td>
                <td>Đơn vị tính</td>
                <td>Tổng tiền</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Details)
            {
                if (item.InvoiceType == InventoryManagement.Commons.Enums.InvoiceTypeEnum.ReturnInvoice)
                {
                    <tr>
                        <td><a @Url.Action("Update", "Product", new { id = item.Id })>@Html.DisplayFor(modelItem => item.Name)</a></td>
                        <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                        <td>@Html.DisplayFor(modelItem => item.Unit)</td>
                        <td>@Html.DisplayFor(modelItem => item.TotalToString)</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</form>

Views/Report/SaleReport.cshtml
@model InventoryManagement.Models.ReportModels.InvoiceReportViewModel
@{
    ViewData["Title"] = "Báo cáo xuất kho";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form asp-action="SaleReport" method="get">
    <table id="tblAdd" style="width:100%;" cellpadding="0" cellspacing="1">
        <tr class="tr-view">
            <td class="td-view-right">
                <a href="@Url.Action("SaleReportToPdf", "Report", new { startDate = Model.StartDate, endDate = Model.EndDate})" class="button btn-add">In báo cáo</a>
            </td>
            <td class="td-view-left d-flex align-items-center">
                <input type="submit" id="btnUpdate1" class="button" value="Lọc">
                <div class="ms-3 date-filter">
                    <span style="color:#ccc">Từ: </span>
                    <input type="date" name="endDate" value="@Model.EndDateString" />
                    <span style="color:#ccc">Đến: </span>
                    <input type="date" name="startDate" value="@Model.StartDateString" />
                </div>
            </td>
        </tr>
        <tbody>
            <tr>
                <td class="td1"><div style="width:105px;">Thời gian:</div></td>
                <td class="td2">@Html.DisplayFor(modelItem => modelItem.EndDateString) - @Html.DisplayFor(modelItem => modelItem.StartDateString)</td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Doanh thu:</div></td>
                <td class="td2">@Html.DisplayFor(modelItem => modelItem.TotalAmountToVND)</td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Trả lại:</div></td>
                <td class="td2">@Html.DisplayFor(modelItem => modelItem.TotalReturnAmountToVND)</td>
            </tr>
        </tbody>
    </table>

    <div class="history-table-title">Danh sách hàng đã bán:</div>
    <table class="table table-striped table-bordered dtgrView" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" style="border-style:None;width:100%;border-collapse:collapse;">
        <thead>
            <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                <td>Tên hàng</td>
                <td>Số lượng</td>
                <td>Đơn vị tính</td>
                <td>Tổng tiền</td>
                <td>Tổng tiền thực tế</td>
                <td>Chênh lệch</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Details)
            {
                if (item.InvoiceType == InventoryManagement.Commons.Enums.InvoiceTypeEnum.Invoice)
                {
                    var difference = (item.Total - item.OriginalTotal)/ item.OriginalTotal * 100;
                    var style = difference <= -10 ? "background-color: #f81717; color: #fff" : "";
                    <tr>
                        <td><a @Url.Action("Update", "Product", new { id = item.Id })>@Html.DisplayFor(modelItem => item.Name)</a></td>
                        <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                        <td>@Html.DisplayFor(modelItem => item.Unit)</td>
                        <td>@Html.DisplayFor(modelItem => item.OriginalTotalToString)</td>
                        <td>@Html.DisplayFor(modelItem => item.TotalToString)</td>
                        <td style="@style">@Math.Round((decimal)difference, 2) %</td>
                    </tr>
                }
            }
        </tbody>
    </table>

    <div class="history-table-title">Danh sách trả hàng NCC</div>
    <table class="table table-striped table-bordered dtgrView" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" style="border-style:None;width:100%;border-collapse:collapse;">
        <thead>
            <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                <td>Tên hàng</td>
                <td>Số lượng</td>
                <td>Đơn vị tính</td>
                <td>Tổng tiền</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Details)
            {
                if (item.InvoiceType == InventoryManagement.Commons.Enums.InvoiceTypeEnum.ReturnInvoice)
                {
                    <tr>
                        <td><a @Url.Action("Update", "Product", new { id = item.Id })>@Html.DisplayFor(modelItem => item.Name)</a></td>
                        <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                        <td>@Html.DisplayFor(modelItem => item.Unit)</td>
                        <td>@Html.DisplayFor(modelItem => item.TotalToString)</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</form>

Views/Report/SaleReport2.cshtml
@model InventoryManagement.Models.ReportModels.InvoiceReportViewModel
@{
    ViewData["Title"] = "Báo cáo doanh thu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form asp-action="SaleReport2" method="get">
    <table id="tblAdd" style="width:100%;" cellpadding="0" cellspacing="1">
        <tr class="tr-view">
            <td class="td-view-right">
                <a href="@Url.Action("ExportSaleReport2ToPdf", "Report", new { startDate = Model.StartDate, endDate = Model.EndDate})" class="button btn-add">In báo cáo</a>
            </td>
            <td class="td-view-left d-flex align-items-center">
                <input type="submit" id="btnUpdate1" class="button" value="Lọc">
                <div class="ms-3 date-filter">
                    <span style="color:#ccc">Từ: </span>
                    <input type="date" name="endDate" value="@Model.EndDateString" />
                    <span style="color:#ccc">Đến: </span>
                    <input type="date" name="startDate" value="@Model.StartDateString" />
                </div>
            </td>
        </tr>
        <tbody>
            <tr>
                <td class="td1"><div style="width:105px;">Thời gian:</div></td>
                <td class="td2">@Html.DisplayFor(modelItem => modelItem.EndDateString) - @Html.DisplayFor(modelItem => modelItem.StartDateString)</td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Tổng tiền:</div></td>
                <td class="td2">@Html.DisplayFor(modelItem => modelItem.TotalAmountToVND)</td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Tổng tiền thực tế:</div></td>
                <td class="td2">@Html.DisplayFor(modelItem => modelItem.OriginalTotalAmountToVND)</td>
            </tr>
        </tbody>
    </table>

    <div class="history-table-title">Danh sách hàng đã bán</div>
    <table class="table table-striped table-bordered dtgrView" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" style="border-style:None;width:100%;border-collapse:collapse;">
        <thead>
            <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                <td>Tên hàng</td>
                <td>Số lượng</td>
                <td>Đơn vị tính</td>
                <td>Tổng tiền</td>
                <td>Tổng tiền thực tế</td>
                <td>Chênh lệch</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Details)
            {
                if (item.InvoiceType == InventoryManagement.Commons.Enums.InvoiceTypeEnum.Invoice)
                {
                    var difference = (item.Total - item.OriginalTotal) / item.OriginalTotal * 100;
                    var style = difference <= -10 ? "background-color: #f81717; color: #fff" : "";
                    <tr>
                        <td><a @Url.Action("Update", "Product", new { id = item.Id })>@Html.DisplayFor(modelItem => item.Name)</a></td>
                        <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                        <td>@Html.DisplayFor(modelItem => item.Unit)</td>
                        <td>@Html.DisplayFor(modelItem => item.OriginalTotalToString)</td>
                        <td>@Html.DisplayFor(modelItem => item.TotalToString)</td>
                        <td style="@style">@Math.Round((decimal)difference, 2) %</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</form>