Models/PartnerModels/PartnerViewModel.cs
using InventoryManagement.Commons.Enums;

namespace InventoryManagement.Models.PartnerModels
{
    public class PartnerViewModel
    {
        public string Id { get; set; }

        public string FullName { get; set; }
        public string? Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }

        public ActiveEnum IsActive { get; set; }
    }
}

Controllers/PartnerController.cs
using InventoryManagement.Commons.Extensions;
using InventoryManagement.Models.CommonModels;
using InventoryManagement.Models.PartnerModels;
using InventoryManagement.Services.Contractors;
using InventoryManagement.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagement.Controllers
{
    [Authorize(Policy = "admin")]
    public class PartnerController : Controller
    {
        private readonly IPartnerService _partnerService;
        private readonly IPurchaseInvoiceService _purchaseInvoiceService;
        private readonly ISaleInvoiceService _saleInvoiceService;

        public PartnerController(IPartnerService partnerService, 
            IPurchaseInvoiceService purchaseInvoiceService, 
            ISaleInvoiceService saleInvoiceService)
        {
            _partnerService = partnerService;
            _purchaseInvoiceService = purchaseInvoiceService;
            _saleInvoiceService = saleInvoiceService;
        }

        [Breadcrumb("", "Đối tác")]
        public async Task<IActionResult> Index()
        {
            if (TempData["ToastNotify"] != null)
            {
                ToastViewModel tempData = TempData.Get<ToastViewModel>("ToastNotify");
                ViewData["ToastNotify"] = tempData;
            }

            var response = await _partnerService.All();

            return View(response.data);
        }

        [Authorize(Policy = "admin")]
        public async Task<IActionResult> All()
        {
            var response = await _partnerService.All();

            if (response.data != null)
            {
                return Ok(response.data);
            }

            return BadRequest();
        }

        [Breadcrumb("Thông tin chi tiết", "Đối tác")]
        public async Task<IActionResult> Detail(string id)
        {
            var partner = await _partnerService.Get(id);
            var purchaseInvoice = await _purchaseInvoiceService.GetByPartnerIdAsync(id);
            var returnInvoice = await _saleInvoiceService.GetReturnInvoiceByPartnerIdAsync(id);

            if (!partner.isSuccess || !purchaseInvoice.isSuccess || !returnInvoice.isSuccess)
            {
                TempData.Put("ToastNotify", new ToastViewModel()
                {
                    IsSuccess = false,
                    Message = "Không tìm thấy thông tin!",
                });

                return RedirectToAction(nameof(Index));
            }

            var model = new PartnerDetailViewModel()
            {
                Partner = partner.data,
                PurchaseInvoices = purchaseInvoice.data,
                ReturnInvoices = returnInvoice.data,
            };

            return View(model);
        }

        [Breadcrumb("Thêm mới", "Đối tác")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePartnerRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var response = await _partnerService.Create(request);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = response.isSuccess,
                Message = response.Message,
            });

            if (!response.isSuccess)
            {
                return View(request);
            }

            return RedirectToAction(nameof(Index));
        }

        [Breadcrumb("Cập nhật", "Đối tác")]
        public async Task<IActionResult> Update(string id)
        {
            var res = await _partnerService.Get(id);

            if(!res.isSuccess)
            {
                return RedirectToAction(nameof(Index));
            }

            var partner = res.data;

            var data = new UpdatePartnerRequest()
            {
                Id = id,
                FullName = partner.FullName,
                Company = partner.Company,
                PhoneNumber = partner.PhoneNumber,
                Email = partner.Email,
                Address = partner.Address,
                IsActive = partner.IsActive,
            };

            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdatePartnerRequest request)
        {
            if (!ModelState.IsValid)
                return View(request);

            var response = await _partnerService.Update(request);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = response.isSuccess,
                Message = response.Message,
            });

            if (!response.isSuccess)
            {
                ModelState.AddModelError("", response.Message != null ? response.Message : "");
                return View(request);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string id)
        {
            var res = await _partnerService.Delete(id);

            TempData.Put("ToastNotify", new ToastViewModel()
            {
                IsSuccess = res.isSuccess,
                Message = res.Message,
            });

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Partner/Create.cshtml
@using InventoryManagement.Models.PartnerModels
@model CreatePartnerRequest
@{
    ViewData["Title"] = "Thêm nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Create" method="post">
    <table id="tblAdd" style="width:100%;" cellpadding="0" cellspacing="1">
        <tbody>
            <tr class="tr-view">
                <td colspan="2" class="td-view-left">
                    <input type="submit" value="Ghi nhận" id="btnAddU1" class="button">
                    <input type="reset" class="button" value="Mặc định">
                </td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Tên công ty:</div></td>
                <td class="td2"><input type="text" maxlength="150" asp-for="Company" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Nhân viên:</div></td>
                <td class="td2"><input type="text" maxlength="150" asp-for="FullName" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Địa chỉ:</div></td>
                <td class="td2"><input type="text" maxlength="150" asp-for="Address" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Hotline:</div></td>
                <td class="td2"><input type="tel" maxlength="150" asp-for="PhoneNumber" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Email:</div></td>
                <td class="td2"><input type="email" maxlength="150" asp-for="Email" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1">&nbsp;</td>
                <td class="td1" style="text-align:left;">
                    <input type="submit" value="Ghi nhận" class="button" style="width:100px;">
                    <input type="reset" class="button" value="Mặc định" style="width:100px;">
                </td>
            </tr>
        </tbody>
    </table>
</form>

Views/Partner/Detail.cshtml
@model InventoryManagement.Models.PartnerModels.PartnerDetailViewModel
@{
    ViewData["Title"] = "Thông tin nhà cung cấp " + Model.Partner.Company;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="tblAdd" style="width:100%;" cellpadding="0" cellspacing="1">
    <tbody>
        <tr>
            <td class="td1"><div style="width:105px;">Tên công ty:</div></td>
            <td class="td2"><input value="@Model.Partner.Company" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
        </tr>
        <tr>
            <td class="td1"><div style="width:105px;">Tên nhân viên đại diện:</div></td>
            <td class="td2"><input value="@Model.Partner.FullName" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
        </tr>
        <tr>
            <td class="td1"><div style="width:105px;">Địa chỉ:</div></td>
            <td class="td2"><input value="@Model.Partner.Address" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
        </tr>
        <tr>
            <td class="td1"><div style="width:105px;">Hotline:</div></td>
            <td class="td2"><input value="@Model.Partner.PhoneNumber" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
        </tr>
        <tr>
            <td class="td1"><div style="width:105px;">Email:</div></td>
            <td class="td2"><input value="@Model.Partner.Email" type="text" maxlength="150" class="textbox" style="width: 250px;"></td>
        </tr>
    </tbody>
</table>

<div class="history-table-title">Lịch sử nhập hàng</div>
<table class="table table-striped table-bordered dtgrView" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" style="border-style:None;width:100%;border-collapse:collapse;">
    <thead>
        <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
            <td>Nhân viên lập</td>
            <td>Tình trạng</td>
            <td>Ngày lập</td>
            <td>Tổng tiền</td>
            <td style="width:10px;">&nbsp;Chi tiết&nbsp;</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.PurchaseInvoices)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                <td>@Html.DisplayFor(modelItem => item.Status)</td>
                <td>@Html.DisplayFor(modelItem => item.CreateAtString)</td>
                <td>@Html.DisplayFor(modelItem => item.TotalToVND) VNĐ</td>
                <td align="center"><a href="@Url.Action("Detail", "PurchaseInvoice", new { id = item.Id })"><img border="0" src="/iconcp/preview.png"></a></td>
            </tr>
        }
    </tbody>
</table>

<div class="history-table-title">Lịch sử trả hàng</div>
<table class="table table-striped table-bordered dtgrView" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" style="border-style:None;width:100%;border-collapse:collapse;">
    <thead>
        <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
            <td>Nhân thực hiện</td>
            <td>Tình trạng</td>
            <td>Ngày lập</td>
            <td>Tổng tiền</td>
            <td style="width:10px;">&nbsp;Chi tiết&nbsp;</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ReturnInvoices)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                <td>@Html.DisplayFor(modelItem => item.Status)</td>
                <td>@Html.DisplayFor(modelItem => item.CreateAtString)</td>
                <td>@Html.DisplayFor(modelItem => item.TotalToVND) VNĐ</td>
                <td align="center"><a href="@Url.Action("Detail", "SaleInvoice", new { id = item.Id })"><img border="0" src="/iconcp/preview.png"></a></td>
            </tr>
        }
    </tbody>
</table>

Views/Partner/Index.cshtml
@using InventoryManagement.Commons.Enums
@model List<InventoryManagement.Models.PartnerModels.PartnerViewModel>
@{
    ViewData["Title"] = "Danh mục nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="tblView" style="width:100%;" cellpadding="0" cellspacing="0">
    <tbody>
        <tr class="tr-view">
            <td class="td-view-left">
            </td>
            <td class="td-view-right">
                <a asp-action="Create" class="button btn-add">Thêm mới</a>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table class="table table-striped table-bordered" cellspacing="0" cellpadding="3" align="Center" rules="all" border="1" id="dtgrView" style="border-style:None;width:100%;border-collapse:collapse;">
                    <thead>
                        <tr class="header" style="background-color:#F4F4F4;font-weight:bold;">
                            <td>Tên</td>
                            <td>Nhân viên đại diện</td>
                            <td>Địa chỉ</td>
                            <td>SĐT</td>
                            <td>Email</td>
                            <td>Hiện</td>
                            <td style="width:10px;">&nbsp;Chi tiết&nbsp;</td>
                            <td style="width:10px;">&nbsp;Sửa&nbsp;</td>
                            <td style="width:10px;">&nbsp;Xóa&nbsp;</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            var activeEnums = Enum.GetValues(typeof(ActiveEnum));
                         <tr>
                             <td>@Html.DisplayFor(modelItem => item.Company)</td>
                             <td>@Html.DisplayFor(modelItem => item.FullName)</td>
                             <td>@Html.DisplayFor(modelItem => item.Address)</td>
                             <td>@Html.DisplayFor(modelItem => item.PhoneNumber)</td>
                             <td>@Html.DisplayFor(modelItem => item.Email)</td>
                             <td>
                                 <select name="dtgrView$ctl03$drlAc" id="dtgrView_drlAc_0" class="textbox drl">
                                     @for (int i = 0; i < activeEnums.Length; i++)
                                     {
                                         var selected = item.IsActive == (ActiveEnum)i ? "selected" : "";
                                         <option value="@i" selected="@selected">@activeEnums.GetValue(i)</option>
                                     }
                                 </select>
                             </td>
                             <td align="center"><a href="@Url.Action("Detail", "Partner", new { id = item.Id })"><img border="0" src="/iconcp/preview.png"></a></td>
                             <td align="center"><a href="@Url.Action("Update", "Partner", new { id = item.Id })"><img border="0" src="/iconcp/icon_edit.gif"></a></td>
                             <td align="center"><a href="@Url.Action("Delete", "Partner", new { id = item.Id })" onclick="javascript:return confirm('Bạn chắc chắn muốn xoá Đối tác không?');"><img border="0" src="/iconcp/icon_delete.gif"></a></td>
                         </tr>
                        }
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>

Views/Partner/Update.cshtml
@using InventoryManagement.Models.PartnerModels 
@using InventoryManagement.Commons.Enums
@model UpdatePartnerRequest
@{
    ViewData["Title"] = "Cập nhật thông tin nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Update" method="post">
    <input type="hidden" value="@Model.Id" asp-for="Id" />
    <table id="tblAdd" style="width:100%;" cellpadding="0" cellspacing="1">
        <tbody>
            <tr class="tr-view">
                <td colspan="2" class="td-view-left">
                    <input type="submit" value="Ghi nhận" id="btnAddU1" class="button">
                    <input type="reset" class="button" value="Mặc định">
                </td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Tên công ty:</div></td>
                <td class="td2"><input value="@Model.Company" type="text" maxlength="150" asp-for="Company" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Tên nhân viên đại diện:</div></td>
                <td class="td2"><input value="@Model.FullName" type="text" maxlength="150" asp-for="FullName" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Địa chỉ:</div></td>
                <td class="td2"><input value="@Model.Address" type="text" maxlength="150" asp-for="Address" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Hotline:</div></td>
                <td class="td2"><input value="@Model.PhoneNumber" type="tel" maxlength="150" asp-for="PhoneNumber" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Email:</div></td>
                <td class="td2"><input value="@Model.Email" type="email" maxlength="150" asp-for="Email" class="textbox" style="width: 250px;"></td>
            </tr>
            <tr>
                <td class="td1"><div style="width:105px;">Trạng Thái:</div></td>
                <td class="td2" style="line-height:180%;">
                    @{
                        var activeEnums = Enum.GetValues(typeof(ActiveEnum));

                        for (int i = 0; i < activeEnums.Length; i++)
                        {
                            var check = Model.IsActive == (ActiveEnum)i ? "checked" : "";
                            var text = ActiveEnum.Active == (ActiveEnum)i ? "Hiện" : "Ẩn";
                            <input asp-for="IsActive" value="@i" checked ="@check" tabindex="1" type="radio"><label asp-for="IsActive">@text</label><br>
                        }
                    }
                </td>
            </tr>
            <tr>
                <td class="td1">&nbsp;</td>
                <td class="td1" style="text-align:left;">
                    <input type="submit" value="Ghi nhận" class="button" style="width:100px;">
                    <input type="reset" class="button" value="Mặc định" style="width:100px;">
                </td>
            </tr>
        </tbody>
    </table>
</form>